### ISSUE TITLE
Recorded File type 3gp instead of aac

### ISSUE THREAD

**Issue by Shafichariri** [Piasy/RxAndroidAudio#8]
Hello, so RxAndroidAudio (Great library) to implement my voice note recorder. Everything was straight forward and easy, except for one thing the output file type.

I required my file to be upload to the web and be played by the HTML5 AUDIO tag, which supports aac.

My rxAndroidAudio recorder Settings are the following:

mAudioRecorder.prepareRecord(MediaRecorder.AudioSource.MIC,
                                    MediaRecorder.OutputFormat.MPEG_4, 
                                    MediaRecorder.AudioEncoder.AAC, 
                                   16000, 
                                   16000,
                                   mAudioFile);

Yet, still I get file of 3gp type and the mimetype is video/mp4.
- Is this normal?
- Is there a way I can get mimetype audio/mp4 and file type aac or mp4 or m4a?

Thanks

**Comment by Piasy** [comment]
I use almost the same code as yours:

``` java
mAudioRecorder.prepareRecord(MediaRecorder.AudioSource.MIC,
                                MediaRecorder.OutputFormat.MPEG_4, MediaRecorder.AudioEncoder.AAC,
                                mAudioFile)
```

And just name the `mAudioFile` as `.m4a`, then its mime type is `audio/x-m4a`.

**Comment by Shafichariri** [comment]
Thanks for the quick reply :) Much appreciated.
I added the m4a but nothing changed.

So apparently it is not working on Android 4.4.2 (LG). 
I tested on Android 5.0.1 and Android 6 it worked.....
I still can't find the issue, might it be a compatibility issue?

**Comment by Piasy** [comment]
Could be, I use 6.0 for test, I'll test it on 4.4 tomorrow.

**Comment by Shafichariri** [comment]
Hey, I debugged more on older Android versions (4.1):

I got the following error when trying to play the audio file I recorded (on Android 4.1):

 D/RxAudioPlayer: MediaPlayer to start play: primaryVoiceNote.m4a
 E/MediaPlayer: Unable to to create media player
 W/RxAudioPlayer: startPlay fail, IllegalArgumentException: setDataSourceFD failed.: status=0x80000000
 E/MediaPlayer: stop called in state 1
 E/MediaPlayer: error (-38, 0)
 E/BaseApplication: RxJavaPlugins
                                            java.io.IOException: setDataSourceFD failed.: status=0x80000000
                                                at android.media.MediaPlayer.setDataSource(Native Method)
                                                at android.media.MediaPlayer.setDataSource(MediaPlayer.java:976)
                                                at android.media.MediaPlayer.setDataSource(MediaPlayer.java:955)
                                                at android.media.MediaPlayer.setDataSource(MediaPlayer.java:918)
                                                at com.github.piasy.rxandroidaudio.RxAudioPlayer$1.call(RxAudioPlayer.java:99)
                                                at com.github.piasy.rxandroidaudio.RxAudioPlayer$1.call(RxAudioPlayer.java:91)
                                                at rx.Single$1.call(Single.java:94)
                                                at rx.Single$1.call(Single.java:74)
                                                at rx.Single.subscribe(Single.java:1822)
                                                at rx.Single.subscribe(Single.java:1899)
                                                at rx.Single$5$1.onSuccess(Single.java:697)
                                                at rx.Single$5$1.onSuccess(Single.java:693)
                                                at rx.Single$18.onNext(Single.java:1894)
                                                at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
                                                at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
                                                at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
                                                at rx.Single$1$1.onSuccess(Single.java:84)
                                                at rx.internal.util.ScalarSynchronousSingle$ScalarSynchronousSingleAction.call(ScalarSynchronousSingle.java:120)
                                                at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
                                                at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
                                                at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                                at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                at java.lang.Thread.run(Thread.java:856)
com.shafic.application.debug E/BaseApplication: RxJavaPlugins
                                            java.io.IOException: setDataSourceFD failed.: status=0x80000000
                                                at android.media.MediaPlayer.setDataSource(Native Method)
                                                at android.media.MediaPlayer.setDataSource(MediaPlayer.java:976)
                                                at android.media.MediaPlayer.setDataSource(MediaPlayer.java:955)
                                                at android.media.MediaPlayer.setDataSource(MediaPlayer.java:918)
                                                at com.github.piasy.rxandroidaudio.RxAudioPlayer$1.call(RxAudioPlayer.java:99)
                                                at com.github.piasy.rxandroidaudio.RxAudioPlayer$1.call(RxAudioPlayer.java:91)
                                                at rx.Single$1.call(Single.java:94)
                                                at rx.Single$1.call(Single.java:74)
                                                at rx.Single.subscribe(Single.java:1822)
                                                at rx.Single.subscribe(Single.java:1899)
                                                at rx.Single$5$1.onSuccess(Single.java:697)
                                                at rx.Single$5$1.onSuccess(Single.java:693)
                                                at rx.Single$18.onNext(Single.java:1894)
                                                at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
                                                at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
                                                at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
                                                at rx.Single$1$1.onSuccess(Single.java:84)
                                                at rx.internal.util.ScalarSynchronousSingle$ScalarSynchronousSingleAction.call(ScalarSynchronousSingle.java:120)
                                                at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
                                                at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
                                                at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                                at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                at java.lang.Thread.run(Thread.java:856)
com.shafic.application.debug E/AudioRecorderView: Could not start Playing file. Playing failed.
                                              mAudioFile: /mnt/sdcard/Android/data/com.shafic.application.debug/files/Music/primaryVoiceNote.m4a
                                              java.io.IOException: setDataSourceFD failed.: status=0x80000000
                                                  at android.media.MediaPlayer.setDataSource(Native Method)
                                                  at android.media.MediaPlayer.setDataSource(MediaPlayer.java:976)
                                                  at android.media.MediaPlayer.setDataSource(MediaPlayer.java:955)
                                                  at android.media.MediaPlayer.setDataSource(MediaPlayer.java:918)
                                                  at com.github.piasy.rxandroidaudio.RxAudioPlayer$1.call(RxAudioPlayer.java:99)
                                                  at com.github.piasy.rxandroidaudio.RxAudioPlayer$1.call(RxAudioPlayer.java:91)
                                                  at rx.Single$1.call(Single.java:94)
                                                  at rx.Single$1.call(Single.java:74)
                                                  at rx.Single.subscribe(Single.java:1822)
                                                  at rx.Single.subscribe(Single.java:1899)
                                                  at rx.Single$5$1.onSuccess(Single.java:697)
                                                  at rx.Single$5$1.onSuccess(Single.java:693)
                                                  at rx.Single$18.onNext(Single.java:1894)
                                                  at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                  at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
                                                  at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
                                                  at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
                                                  at rx.Single$1$1.onSuccess(Single.java:84)
                                                  at rx.internal.util.ScalarSynchronousSingle$ScalarSynchronousSingleAction.call(ScalarSynchronousSingle.java:120)
                                                  at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
                                                  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
                                                  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                                  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
                                                  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                  at java.lang.Thread.run(Thread.java:856)

After some googling I understood that this might have to do with Settings of recorder, so I changed the settings to:
..MediaRecorder.OutputFormat.THREE_GPP, MediaRecorder.AudioEncoder.AMR_NB,..

I was able to get rid of the error but still I could not play the file I recorded.

**Comment by SuperXFan** [comment]
How to monitor the sound level during recording and play？

**Comment by Piasy** [comment]
@SuperXFan You can use `RxAmplitude` to get sound level during recording, but no way to do it during playing.

**Comment by Piasy** [comment]
Going to close it, feel free to reopen :)
